import re

BLOCKED_COMMANDS = [
    "delete system32",
    "format c:",
    "rm -rf",
    "sudo",
    "mkfs",
    "del /s /q",
    "wipe"
]

def sanitize_command(text: str) -> tuple[str | None, str | None]:
    """
    Checks if a system command dynamically generated by the user or the LLM
    contains inherently destructive or highly elevated system tasks.
    Returns (safe_text, err_msg)
    """
    if not text:
        return text, None
        
    lower_text = text.lower()
    
    # Normalize: strip out quotes, backticks, backslashes and redundant spaces
    normalized = re.sub(r'[\'"`\\]', '', lower_text)
    normalized_clean = re.sub(r'\s+', ' ', normalized).strip()
    normalized_no_spaces = normalized_clean.replace(" ", "")

    for blocked in BLOCKED_COMMANDS:
        blocked_clean = blocked.lower()
        blocked_no_spaces = blocked_clean.replace(" ", "")
        
        if (blocked_clean in lower_text or 
            blocked_clean in normalized_clean or 
            blocked_no_spaces in normalized_no_spaces):
            return None, f"Dangerous command blocked: '{blocked}' is strictly prohibited by security permissions."
            
    return text, None
