BLOCKED_COMMANDS = [
    "delete system32",
    "format c:",
    "rm -rf",
    "sudo",
    "admin",
    "mkfs",
    "del /s /q",
    "wipe"
]

def sanitize_command(text: str) -> tuple[str | None, str | None]:
    """
    Checks if a system command dynamically generated by the user or the LLM
    contains inherently destructive or highly elevated system tasks.
    Returns (safe_text, err_msg)
    """
    if not text:
        return text, None
        
    lower_text = text.lower()
    for blocked in BLOCKED_COMMANDS:
        if blocked in lower_text:
            return None, f"Dangerous command blocked: '{blocked}' is strictly prohibited by security permissions."
            
    return text, None
