from __future__ import annotations

import hashlib
import json
import shutil
import sys
import zipfile
from pathlib import Path

from core.version import APP_NAME, APP_VERSION


ROOT = Path(__file__).resolve().parent.parent
DIST_DIR = ROOT / "dist"
SOURCE_DIR = DIST_DIR / "Kree AI"
RELEASE_DIR = DIST_DIR / "release"
STAGE_DIR = RELEASE_DIR / "stage"
PACKAGE_NAME = f"Kree-AI-v{APP_VERSION}-win64.zip"
PACKAGE_PATH = RELEASE_DIR / PACKAGE_NAME
MANIFEST_PATH = RELEASE_DIR / "kree-update-manifest.json"
README_SRC = ROOT / "README-INSTALL.txt"


def _copy_tree_without_config(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for item in source.iterdir():
        if item.name.lower() == "config":
            continue
        target = destination / item.name
        if item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True)
        else:
            shutil.copy2(item, target)


def _zip_directory(source: Path, destination: Path) -> None:
    if destination.exists():
        destination.unlink()
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in source.rglob("*"):
            if path.is_dir():
                continue
            archive.write(path, path.relative_to(source))


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    if not SOURCE_DIR.exists():
        print(f"Release source folder not found: {SOURCE_DIR}")
        return 1

    if STAGE_DIR.exists():
        shutil.rmtree(STAGE_DIR)
    RELEASE_DIR.mkdir(parents=True, exist_ok=True)

    staged_app = STAGE_DIR / "Kree AI"
    _copy_tree_without_config(SOURCE_DIR, staged_app)

    # Include README-INSTALL.txt in the release
    if README_SRC.exists():
        shutil.copy2(README_SRC, staged_app / "README-INSTALL.txt")

    _zip_directory(staged_app, PACKAGE_PATH)

    manifest = {
        "name": APP_NAME,
        "version": APP_VERSION,
        "package_type": "zip",
        "download_url": PACKAGE_NAME,
        "sha256": _sha256(PACKAGE_PATH),
        "notes": "Portable Windows release bundle generated by the local build pipeline.",
        "published_at": "",
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(f"Created release bundle: {PACKAGE_PATH}")
    print(f"Created manifest: {MANIFEST_PATH}")

    # Clean up staging
    if STAGE_DIR.exists():
        shutil.rmtree(STAGE_DIR, ignore_errors=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
